[window]
padding.x = 10
padding.y = 10

decorations = 'Buttonless'

option_as_alt = 'Both'

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 13.8

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "source ~/.zshrc; tmux attach 2> /dev/null || tmux"]
