[window]
padding.x = 10
padding.y = 10

decorations = 'Buttonless'

option_as_alt = 'Both'

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 14.2
offset.y = 3

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "source ~/.zshrc; tmux attach 2> /dev/null || tmux"]

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

[scrolling]
history = 1

# Colors - https://github.com/olimorris/onedarkpro.nvim
[colors.primary]
background= '#282c34'
foreground= '#abb2bf'

[colors.normal]
black=      '#282c34'
red=        '#e06c75'
green=      '#98c379'
yellow=     '#e5c07b'
blue=       '#61afef'
magenta=    '#c678dd'
cyan=       '#56b6c2'
white=      '#abb2bf'

[colors.bright]
black=      '#5c6370'
red=        '#2121ff'
green=      '#2222ff'
yellow=     '#000041'
blue=       '#00003e'
